"use client";

import { useState } from "react";
import { Card } from "@/components/primitives/Card";
import { Button } from "@/components/primitives/Button";
import { Chip } from "@/components/primitives/Chip";
import { Label, Divider } from "@/components/primitives/Label";
import { Textarea } from "@/components/primitives/Input";
import { FitRing } from "@/components/fit/FitRing";
import { SkillRadar } from "@/components/fit/SkillRadar";
import { CompPositioning } from "@/components/charts/CompPositioning";
import type { MockJob } from "@/lib/data/mock";

type Tab = "overview" | "letter" | "ats" | "interview";

const TABS: { id: Tab; label: string }[] = [
  { id: "overview", label: "Overview" },
  { id: "letter", label: "Cover Letter" },
  { id: "ats", label: "ATS Resume" },
  { id: "interview", label: "Interview Notes" },
];

export function JobDetail({ job, provider }: { job: MockJob; provider: string }) {
  const [tab, setTab] = useState<Tab>("overview");
  const [notes, setNotes] = useState(
    "Phone screen with Karri felt strong on technical depth. They pushed on design-system governance — could go deeper. Next round: take-home (graph view).",
  );
  const [evaluating, setEvaluating] = useState(false);

  return (
    <div className="grid grid-cols-1 gap-6 lg:grid-cols-[1.4fr_1fr]">
      {/* Left column */}
      <div className="flex flex-col gap-4.5">
        <Card ticks className="relative p-5.5">
          <div className="flex items-start justify-between gap-6">
            <div className="flex-1">
              <Label className="mb-1.5 block">
                JOB ID · {job.id} · ANALYZED 12:07:14 · {provider.toUpperCase()}
              </Label>
              <h1 className="m-0 text-[28px] font-extrabold tracking-[-0.01em]">{job.jobTitle}</h1>
              <div className="text-fg-2 mt-2 flex flex-wrap gap-3.5 text-[13px]">
                <span className="text-fg-0 font-semibold">{job.company}</span>
                <span>·</span>
                <span>{job.location}</span>
                <span>·</span>
                <span>{job.salaryRange}</span>
              </div>
              <div className="mt-3.5 flex flex-wrap gap-1.5">
                {job.tags.map((t) => (
                  <Chip key={t}>{t}</Chip>
                ))}
              </div>
            </div>
            <FitRing value={job.fitScore} size={120} />
          </div>

          <Divider />
          <div className="flex flex-wrap gap-2.5">
            <Button variant="primary">Apply with tailored kit →</Button>
            <Button>↓ Download cover letter</Button>
            <Button>↓ Download ATS resume</Button>
            <Button variant="ghost" className="ml-auto">
              ↗ Open posting
            </Button>
          </div>
        </Card>

        <div className="border-line flex border-b">
          {TABS.map((t) => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={`-mb-px border-b-2 bg-none px-4 py-2.5 text-[12px] tracking-[0.06em] uppercase transition ${
                tab === t.id
                  ? "border-accent text-fg-0"
                  : "text-fg-3 hover:text-fg-1 border-transparent"
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>

        {tab === "overview" && (
          <>
            <Card className="p-4.5">
              <Label>match reasoning</Label>
              <p className="text-fg-1 mt-2 mb-0 leading-relaxed">{job.matchReasoning}</p>
            </Card>
            <Card className="p-4.5">
              <Label className="mb-2.5 block">skill gaps · ranked by impact</Label>
              {job.gaps.map((g, i) => (
                <div
                  key={g}
                  className={`grid grid-cols-[24px_1fr_100px] items-center gap-2.5 py-2 ${
                    i ? "border-line-soft border-t" : ""
                  }`}
                >
                  <span className="text-accent font-bold">{`0${i + 1}`}</span>
                  <span className="text-fg-1">{g}</span>
                  <span className="text-fg-3 text-right text-[11px]">~{[3, 2][i] || 2}w to close</span>
                </div>
              ))}
            </Card>
          </>
        )}

        {tab === "letter" && (
          <Card className="p-5.5 leading-relaxed whitespace-pre-wrap">
            <Label className="mb-3.5 block">cover_letter.md · generated by {provider}</Label>
            <div className="text-fg-1" style={{ fontFamily: "Georgia, serif", fontSize: 14 }}>
              {job.coverLetter ?? "Not yet generated."}
            </div>
          </Card>
        )}

        {tab === "ats" && (
          <Card className="p-5.5">
            <Label className="mb-3.5 block">
              ats_resume.txt · keyword-tuned for &quot;{job.jobTitle} · {job.company}&quot;
            </Label>
            <pre className="text-fg-1 m-0 text-[12px] leading-relaxed whitespace-pre-wrap">{`JOHN SMITH — ${job.jobTitle}
SF Bay · john.smith@email.com · linkedin.com/in/johnsmith

SUMMARY
Senior frontend engineer (5y) building React + TypeScript design
systems at scale. Led platform serving 10k+ daily users; shipped
AI features that lifted engagement 40%.

CORE COMPETENCIES
React · TypeScript · Design Systems · Performance · Tooling · Motion
Storybook · Vite · CI/CD · Visual Regression · Telemetry · A11y

EXPERIENCE
TechCorp Inc. — Sr. Software Engineer ........ 2021—present
  • Architected design system used by 12 product squads
  • Cut TTI 38% on dashboard via lazy-graph + RSC migration
  • Owned visual-regression pipeline (Chromatic) end-to-end

StartupXYZ — Software Engineer ............... 2019—2021
  • Shipped TS-strict component library across 4 surfaces
  • Drove perf budget program, p75 LCP < 1.8s`}</pre>
          </Card>
        )}

        {tab === "interview" && (
          <Card className="p-4.5">
            <Label className="mb-2.5 block">your notes · post-interview</Label>
            <Textarea
              rows={6}
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              className="font-mono text-[12px] leading-relaxed"
            />
            <div className="mt-3 flex gap-2.5">
              <Button
                variant="primary"
                onClick={() => {
                  setEvaluating(true);
                  setTimeout(() => setEvaluating(false), 1400);
                }}
              >
                {evaluating ? "Evaluating…" : "Evaluate vs market →"}
              </Button>
              <Button variant="ghost">Save draft</Button>
            </div>
            <Divider />
            <Label>market evaluation · {provider}</Label>
            <p className="text-fg-1 mt-2 leading-relaxed">
              Strong technical signal aligns with Linear&apos;s IC4–IC5 bar. The design-system governance gap is real
              and common at this level — 64% of Staff candidates flag it. Recommend a take-home that demonstrates
              system-level decisions (versioning, deprecation), not just component craft.
            </p>
          </Card>
        )}
      </div>

      {/* Right column */}
      <div className="flex flex-col gap-4.5">
        <Card className="p-4.5">
          <div className="flex items-center justify-between">
            <Label>skill radar</Label>
            <div className="text-fg-3 flex gap-3 text-[10px]">
              <span>
                <i className="bg-accent mr-1.5 inline-block h-0.5 w-2.5 align-text-top" />
                you
              </span>
              <span>
                <i className="bg-fg-3 mr-1.5 inline-block h-0.5 w-2.5 align-text-top" />
                required
              </span>
            </div>
          </div>
          <div className="mt-1.5 grid place-items-center">
            <SkillRadar skills={job.skills} size={300} />
          </div>
        </Card>

        <Card className="p-4.5">
          <Label className="mb-2.5 block">compensation · positioning</Label>
          <CompPositioning
            rangeLeftPct={20}
            rangeRightPct={84}
            postedPct={62}
            marketPct={44}
            rangeLowLabel="$210k"
            rangeHighLabel="$260k"
            postedLabel="POSTED $235k"
            marketLabel="MARKET P50 $215k"
          />
          <Divider />
          <div className="text-fg-2 grid grid-cols-2 gap-3 text-[11px]">
            <div>
              <Label>vs your batch</Label>
              <div className="mt-1 text-lg font-bold" style={{ color: "var(--color-sig-good)" }}>
                + $19k
              </div>
              <div className="text-fg-3 text-[10px]">above batch median</div>
            </div>
            <div>
              <Label>vs market p50</Label>
              <div className="mt-1 text-lg font-bold" style={{ color: "var(--color-sig-good)" }}>
                + 9.3%
              </div>
              <div className="text-fg-3 text-[10px]">top quartile</div>
            </div>
          </div>
        </Card>

        <Card className="p-4.5">
          <Label className="mb-2.5 block">signals</Label>
          {(
            [
              ["Resume keyword density", 88, "var(--color-sig-good)"],
              ["Story-relevance match", 76, "var(--color-sig-ok)"],
              ["Seniority alignment", 91, "var(--color-sig-good)"],
              ["Gap recoverability", 72, "var(--color-sig-ok)"],
            ] as const
          ).map(([k, v, c]) => (
            <div
              key={k}
              className="grid grid-cols-[1fr_60px_32px] items-center gap-2.5 py-1.5"
            >
              <span className="text-fg-1 text-[12px]">{k}</span>
              <div className="bg-bg-3 h-1">
                <div className="h-full" style={{ width: `${v}%`, background: c }} />
              </div>
              <span className="text-fg-2 text-right text-[11px]">{v}</span>
            </div>
          ))}
        </Card>
      </div>
    </div>
  );
}
